name: Deploy Stone Dashboard to GitHub Pages

on:
  release:
    types: [created]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Stone Dashboard
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build dashboard static files
        run: |
          mkdir -p dist/dashboard
          ls -la src/dashboard/static/ || true
          
          # Copy static files or create basic dashboard if not found
          if [ -d "src/dashboard/static" ] && [ -f "src/dashboard/static/index.html" ]; then
            echo "Using existing static files"
            cp -r src/dashboard/static/* dist/dashboard/
          else
            echo "Creating basic dashboard page"
            cat > dist/dashboard/index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stone Dashboard</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; margin: 0; padding: 0; line-height: 1.6; }
    .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
    header { background-color: #f4f4f4; padding: 1rem 0; text-align: center; }
    h1 { color: #333; }
    .card { background-color: white; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); padding: 1.5rem; margin-bottom: 1.5rem; }
    .coming-soon { text-align: center; padding: 2rem; background-color: #f9f9f9; border-radius: 5px; margin: 2rem 0; }
  </style>
</head>
<body>
  <header>
    <div class="container">
      <h1>Stone Dashboard</h1>
      <p>A software factory for GitHub-based development using Claude Code</p>
    </div>
  </header>
  
  <div class="container">
    <div class="card">
      <h2>Welcome to Stone</h2>
      <p>Stone is a structured system for orchestrating GitHub-based development using Claude Code. It manages the software development process through specialized roles, each with defined responsibilities and boundaries.</p>
    </div>
    
    <div class="coming-soon">
      <h2>Interactive Dashboard Coming Soon</h2>
      <p>Our interactive dashboard with workflow visualization, metrics, and performance analytics is coming soon.</p>
      <p>Check back for updates or visit our <a href="https://github.com/UOR-Foundation/Stone">GitHub repository</a> for more information.</p>
    </div>
    
    <div class="card">
      <h2>Getting Started</h2>
      <pre>npm install --save-dev @uor-foundation/stone</pre>
      <p>Initialize Stone in your repository:</p>
      <pre>npx stone init</pre>
    </div>
  </div>
</body>
</html>
EOF
          fi
          
          # List the dashboard directory contents for debugging
          echo "Contents of dist/dashboard:"
          ls -la dist/dashboard/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/dashboard'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4