name: Stone Software Factory

on:
  issues:
    types: [labeled, unlabeled, edited]
  pull_request:
    types: [opened, synchronize, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'GitHub issue number to process'
        required: true
        type: number

jobs:
  stone_process: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Install dependencies
        run: pnpm install
      
      - name: Process Stone issue
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            ISSUE_NUMBER="${{ github.event.issue.number }}"
          else
            ISSUE_NUMBER="${{ github.event.inputs.issue_number }}"
          fi

          pnpm stone process --issue $ISSUE_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Handle errors
        if: failure()
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            ISSUE_NUMBER="${{ github.event.issue.number }}"
          else
            ISSUE_NUMBER="${{ github.event.inputs.issue_number }}"
          fi
          
          pnpm stone reset --issue $ISSUE_NUMBER --label stone-manual-intervention
          
          gh issue comment $ISSUE_NUMBER --body "⚠️ **Stone Workflow Error**\n\nThe Stone workflow encountered an error while processing this issue. Manual intervention is required.\n\nPlease check the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dashboard_update:
    runs-on: ubuntu-latest
    needs: stone_process
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Install dependencies
        run: pnpm install
      
      - name: Update dashboard data
        run: pnpm stone dashboard --update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto_rebase:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'stone-feature') && github.event.pull_request.draft == false
    needs: stone_process
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run auto-rebase
        run: pnpm stone auto-rebase --pr ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use a PAT with repo scope for pushing to branches
          STONE_BOT_TOKEN: ${{ secrets.STONE_BOT_TOKEN }}
